apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-config
  namespace: ns-team-ads-test
  labels:
    app: web
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      root /usr/share/nginx/html;
      index index.html;
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
